[package]
name = "automotive"
version = "0.1.1"
edition = "2021"
license = "MIT"
keywords = ["automotive", "CAN", "UDS"]
description = "WIP. Rust crate providing a variety of automotive related libraries, such as communicating with CAN interfaces and diagnostic APIs."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
